// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	models "Gin/models"

	mock "github.com/stretchr/testify/mock"
)

// ICompaniesRepository is an autogenerated mock type for the ICompaniesRepository type
type ICompaniesRepository struct {
	mock.Mock
}

type ICompaniesRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ICompaniesRepository) EXPECT() *ICompaniesRepository_Expecter {
	return &ICompaniesRepository_Expecter{mock: &_m.Mock}
}

// GetCompanies provides a mock function with no fields
func (_m *ICompaniesRepository) GetCompanies() ([]models.Company, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCompanies")
	}

	var r0 []models.Company
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]models.Company, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []models.Company); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Company)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ICompaniesRepository_GetCompanies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCompanies'
type ICompaniesRepository_GetCompanies_Call struct {
	*mock.Call
}

// GetCompanies is a helper method to define mock.On call
func (_e *ICompaniesRepository_Expecter) GetCompanies() *ICompaniesRepository_GetCompanies_Call {
	return &ICompaniesRepository_GetCompanies_Call{Call: _e.mock.On("GetCompanies")}
}

func (_c *ICompaniesRepository_GetCompanies_Call) Run(run func()) *ICompaniesRepository_GetCompanies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ICompaniesRepository_GetCompanies_Call) Return(_a0 []models.Company, _a1 error) *ICompaniesRepository_GetCompanies_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ICompaniesRepository_GetCompanies_Call) RunAndReturn(run func() ([]models.Company, error)) *ICompaniesRepository_GetCompanies_Call {
	_c.Call.Return(run)
	return _c
}

// GetCompany provides a mock function with given fields: companyID
func (_m *ICompaniesRepository) GetCompany(companyID uint) (*models.Company, error) {
	ret := _m.Called(companyID)

	if len(ret) == 0 {
		panic("no return value specified for GetCompany")
	}

	var r0 *models.Company
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*models.Company, error)); ok {
		return rf(companyID)
	}
	if rf, ok := ret.Get(0).(func(uint) *models.Company); ok {
		r0 = rf(companyID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Company)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(companyID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ICompaniesRepository_GetCompany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCompany'
type ICompaniesRepository_GetCompany_Call struct {
	*mock.Call
}

// GetCompany is a helper method to define mock.On call
//   - companyID uint
func (_e *ICompaniesRepository_Expecter) GetCompany(companyID interface{}) *ICompaniesRepository_GetCompany_Call {
	return &ICompaniesRepository_GetCompany_Call{Call: _e.mock.On("GetCompany", companyID)}
}

func (_c *ICompaniesRepository_GetCompany_Call) Run(run func(companyID uint)) *ICompaniesRepository_GetCompany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *ICompaniesRepository_GetCompany_Call) Return(_a0 *models.Company, _a1 error) *ICompaniesRepository_GetCompany_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ICompaniesRepository_GetCompany_Call) RunAndReturn(run func(uint) (*models.Company, error)) *ICompaniesRepository_GetCompany_Call {
	_c.Call.Return(run)
	return _c
}

// PostCompany provides a mock function with given fields: user
func (_m *ICompaniesRepository) PostCompany(user *models.Company) error {
	ret := _m.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for PostCompany")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Company) error); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ICompaniesRepository_PostCompany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostCompany'
type ICompaniesRepository_PostCompany_Call struct {
	*mock.Call
}

// PostCompany is a helper method to define mock.On call
//   - user *models.Company
func (_e *ICompaniesRepository_Expecter) PostCompany(user interface{}) *ICompaniesRepository_PostCompany_Call {
	return &ICompaniesRepository_PostCompany_Call{Call: _e.mock.On("PostCompany", user)}
}

func (_c *ICompaniesRepository_PostCompany_Call) Run(run func(user *models.Company)) *ICompaniesRepository_PostCompany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Company))
	})
	return _c
}

func (_c *ICompaniesRepository_PostCompany_Call) Return(_a0 error) *ICompaniesRepository_PostCompany_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ICompaniesRepository_PostCompany_Call) RunAndReturn(run func(*models.Company) error) *ICompaniesRepository_PostCompany_Call {
	_c.Call.Return(run)
	return _c
}

// NewICompaniesRepository creates a new instance of ICompaniesRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewICompaniesRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ICompaniesRepository {
	mock := &ICompaniesRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
