// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	models "Gin/models"

	mock "github.com/stretchr/testify/mock"
)

// IUsersRepository is an autogenerated mock type for the IUsersRepository type
type IUsersRepository struct {
	mock.Mock
}

type IUsersRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *IUsersRepository) EXPECT() *IUsersRepository_Expecter {
	return &IUsersRepository_Expecter{mock: &_m.Mock}
}

// GetUser provides a mock function with given fields: userID
func (_m *IUsersRepository) GetUser(userID uint) (*models.User, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*models.User, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(uint) *models.User); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IUsersRepository_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type IUsersRepository_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - userID uint
func (_e *IUsersRepository_Expecter) GetUser(userID interface{}) *IUsersRepository_GetUser_Call {
	return &IUsersRepository_GetUser_Call{Call: _e.mock.On("GetUser", userID)}
}

func (_c *IUsersRepository_GetUser_Call) Run(run func(userID uint)) *IUsersRepository_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *IUsersRepository_GetUser_Call) Return(_a0 *models.User, _a1 error) *IUsersRepository_GetUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IUsersRepository_GetUser_Call) RunAndReturn(run func(uint) (*models.User, error)) *IUsersRepository_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUsers provides a mock function with no fields
func (_m *IUsersRepository) GetUsers() ([]models.User, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetUsers")
	}

	var r0 []models.User
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]models.User, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []models.User); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.User)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IUsersRepository_GetUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsers'
type IUsersRepository_GetUsers_Call struct {
	*mock.Call
}

// GetUsers is a helper method to define mock.On call
func (_e *IUsersRepository_Expecter) GetUsers() *IUsersRepository_GetUsers_Call {
	return &IUsersRepository_GetUsers_Call{Call: _e.mock.On("GetUsers")}
}

func (_c *IUsersRepository_GetUsers_Call) Run(run func()) *IUsersRepository_GetUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IUsersRepository_GetUsers_Call) Return(_a0 []models.User, _a1 error) *IUsersRepository_GetUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IUsersRepository_GetUsers_Call) RunAndReturn(run func() ([]models.User, error)) *IUsersRepository_GetUsers_Call {
	_c.Call.Return(run)
	return _c
}

// PostUser provides a mock function with given fields: user
func (_m *IUsersRepository) PostUser(user *models.User) error {
	ret := _m.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for PostUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.User) error); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IUsersRepository_PostUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostUser'
type IUsersRepository_PostUser_Call struct {
	*mock.Call
}

// PostUser is a helper method to define mock.On call
//   - user *models.User
func (_e *IUsersRepository_Expecter) PostUser(user interface{}) *IUsersRepository_PostUser_Call {
	return &IUsersRepository_PostUser_Call{Call: _e.mock.On("PostUser", user)}
}

func (_c *IUsersRepository_PostUser_Call) Run(run func(user *models.User)) *IUsersRepository_PostUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.User))
	})
	return _c
}

func (_c *IUsersRepository_PostUser_Call) Return(_a0 error) *IUsersRepository_PostUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IUsersRepository_PostUser_Call) RunAndReturn(run func(*models.User) error) *IUsersRepository_PostUser_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function with given fields: user
func (_m *IUsersRepository) UpdateUser(user *models.User) error {
	ret := _m.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.User) error); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IUsersRepository_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type IUsersRepository_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - user *models.User
func (_e *IUsersRepository_Expecter) UpdateUser(user interface{}) *IUsersRepository_UpdateUser_Call {
	return &IUsersRepository_UpdateUser_Call{Call: _e.mock.On("UpdateUser", user)}
}

func (_c *IUsersRepository_UpdateUser_Call) Run(run func(user *models.User)) *IUsersRepository_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.User))
	})
	return _c
}

func (_c *IUsersRepository_UpdateUser_Call) Return(_a0 error) *IUsersRepository_UpdateUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IUsersRepository_UpdateUser_Call) RunAndReturn(run func(*models.User) error) *IUsersRepository_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewIUsersRepository creates a new instance of IUsersRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIUsersRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IUsersRepository {
	mock := &IUsersRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
